### ISSUE TITLE
Testing on Windows

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/generator-rest#11]
I've found some problems when trying to `npm test` on Windows.

First, `npm run lint` tries to lint `package.json` files, which obviously throws. The solution would be changing the script to: `"lint": "eslint <%= srcDir %>/**/*.js"` on https://github.com/diegohaz/generator-rest/blob/master/generators/app/templates/_package.json#L14

Another problem is the `test` script itself. It has a condition written in shell script and Windows doesn't recognize it. I'm looking for a cross-platform conditional statement solution, but found nothing yet.

**Comment by diegohaz** [comment]
I think https://github.com/diegohaz/generator-rest/commit/d69c0571b7eb37a1b0266c30d846b90eb67d0cee has fixed this, but I'm having trouble to set up Windows environment to make sure it works.

**Comment by QzSG** [comment]
Managed to finally install bcrypt without errors and am running npm test.
Seems like as the tests run concurrently powershell isn't showing any helpful output. I will report back once the test fails or completes.

**Comment by QzSG** [comment]
@diegohaz The test finished with an error.. :sob: Apparantly it was creating so many copies of the folder to test that it used a few GBs of space.

**Comment by diegohaz** [comment]
It happens because it copies the `node_modules` folder on each test suite. I will change it to create symlinks instead. It will also run faster.
