### ISSUE TITLE
curl -d not found

### ISSUE THREAD

**Issue by raphaelkoszalka** [diegohaz/generator-rest#15]
Hello,

I'm trying to sign in with curl into the API

curl -X POST http://0.0.0.0:9000/auth -i -u test@example.com:123456 -d "access_token=MASTER_KEY_HERE"

But its not working, returns me an error saying that: **-d command not found**

Do i need to update something? (i've already updated curl)

**Comment by diegohaz** [comment]
This is not related with this library itself, but maybe you need to put `test@example.com:123456` in quotes. Which OS are you using?

**Comment by raphaelkoszalka** [comment]
Hi @diegohaz , that solved the problem, thank you.

By the way i'm using ubuntu 16.04.
