### ISSUE TITLE
Model generation from yo rest:api

### ISSUE THREAD

**Issue by serpicolugnut** [diegohaz/generator-rest#2]
While using the yo:rest api tool to create an endpoint, when you get to the model generation part, it asks for a comma separated list of your fields. Is there a way to provide a model that has nested fields/arrays in this setup process?

For example:

-id
-colors
----color_name
----color_value
-categories
---category_name
---category_slug

...and so on.

**Comment by diegohaz** [comment]
You can not do that during the generation of the API from the command line (even we could implement something like this, it would be too complex compared to how easy it's to do the same in javascript).

To add more complexity, you need to go for the code. Once you have generated the API, you can simply open the file `./src/api/api-name.model.js` and change the model to something like this:

```js
const colorSchema = new Schema({
  name: String,
  value: String
})

const categorySchema = new Schema({
  name: String,
  slug: String
})

const articleSchema = new Schema({
  colors: [colorSchema],
  categories: [categorySchema]
})
```

I recommed you to see the mongoose docs for writing schemas/models: http://mongoosejs.com/docs/guide.html

**Comment by serpicolugnut** [comment]
Thanks.
That's what I thought, but I figured I should ask before assuming.

**Comment by diegohaz** [comment]
You're welcome. 😊

**Comment by twlatl** [comment]
One other question: In the generated model file, there is the view block:

`compoundsSchema.methods = {
  view (full) {
    const view = {
      // simple view
      id: this.id,
      id: this.id,
      categories: this.categories,
    }

    return full ? {
      ...view,
      // add properties for a full view
      createdAt: this.createdAt,
      updatedAt: this.updatedAt
    } : view
  }
}`

In the const view obj, how would you reference nested objects and arrays?

**Comment by diegohaz** [comment]
If you mean choosing which properties to show on the categories field, I would use `Array#map`:
```js
categories: this.categories.map(({ id, name }) => ({ id, name })) // omit slug
```

You can also use [lodash's pick](https://lodash.com/docs/4.15.0#pick):
```js
import { pick } from 'lodash'
...
categories: this.categories.map((category) => pick(category, 'id', 'name')) // omit slug
```
