### ISSUE TITLE
Terminations missing

### ISSUE THREAD

**Issue by BernhardBezdek** [diegohaz/generator-rest#20]
On many places the terminatios are is missing which causes warnings in my IDE  (ending lines with ``;``).

This looks optimizable from my POV.

Was there a reason to leave those?
If not maybe I can help you to do a cleanup here.

**Comment by diegohaz** [comment]
Hi, @BernhardBezdek, thank you for the feedback.

This project uses the [Standard Style](http://standardjs.com/). Take a look at this video: https://www.youtube.com/watch?v=gsfbh17Ax9I

It also uses [ESLint](http://eslint.org/) to warn properly (maybe you need to install an eslint plugin for your IDE).

But, if you want to add those semicolons, you can do that easily. Just update the `.eslintrc` file in the root directory of the generated project to look like this:
```json
{
  "parser": "babel-eslint",
  "extends": [
    "standard"
  ],
  "env": {
    "jest": true,
    "jasmine": true
  },
  "rules": {
    "semi": [2, "always"]
  }
}
```

Then, run `npm run lint -- --fix`. It should add the semicolons for you. :)
