### ISSUE TITLE
Add an option to name the user model something else

### ISSUE THREAD

**Issue by jay-at-avido** [diegohaz/generator-rest#21]
Just getting started testing this codebase but it already looks awesome from the get go. :-)
To make it even more awesome, it would be great to add an option to name the _User_ model something else.

For reference, KeystoneJS has this feature on their generator, btw.

The reasoning is that a lot of projects, such as the one I'm working now, support multiple api users under the same paying account, so to model this, instead of a _User_ model I have an _Account_ model (which is the equivalent to the user model you have) and a **Profile** model instead.

**Comment by diegohaz** [comment]
Thank you for your feedback. :)

It would be valuable to have that option. I can do that on this weekend, but If you want to send a PR, I will appreciate very much.

**Comment by diegohaz** [comment]
I've added support for this in the [feature/user-api-name](https://github.com/diegohaz/generator-rest/tree/feature/user-api-name) branch. But this messed up the code a little (I had to add many `<%= userApiName %>` into the files, and maybe it makes the code harder to maintain).

I'll leave it there for awhile and wait for more use cases.
