### ISSUE TITLE
Make Babel dependency optional

### ISSUE THREAD

**Issue by jay-at-avido** [diegohaz/generator-rest#22]
With Node 6.9 supporting  [99% of ES2015](http://node.green), I wonder if still makes sense to force people who are unfamiliar with Babel to use it as a mandatory requirement.

**Comment by diegohaz** [comment]
I can't test it right now, but I think Node v6.9 still doesn't support some stuff this project uses, specially `import`/`export` statements. If you don't mind, remove babel from `src/index.js` and run `npm run dev` to see if it runs without babel.

**Comment by diegohaz** [comment]
Well, I've installed Node 6.9 and tried to run it without Babel and, as expected, it still doesn't support `import` 😭 

I'll close this issue for now, but if someone wants to convert the code to don't depend on Babel, feel free to take this. :)
