### ISSUE TITLE
Rename the ':api' subgenerator to ':endpoint', ':model' or ':resource'

### ISSUE THREAD

**Issue by jay-at-avido** [diegohaz/generator-rest#23]
I'm not a native speaker either, but I think most people would understand API as the complete collection of all related endpoints in a given system or project, while :endpoint would make more sense to describe each individual URL to manipulate a single named resource.

**Comment by diegohaz** [comment]
It seems reasonable. I like `api` because it refers directly to the folder name. I would not change the name though, because it will end up in a huge breaking change. Instead we can create an alias.

**Comment by diegohaz** [comment]
Closing this because it isn't a priority and creating alias with Yeoman isn't trivial. If someone really wants this, I'll accept a PR adding the alias. 👍
