### ISSUE TITLE
Skipping sendgrid information prompt crashes the dev server with missing module error

### ISSUE THREAD

**Issue by jay-at-avido** [diegohaz/generator-rest#25]
This apparently happens if you choose to generate a password reset endpoint but skip the sendgrid information prompt. 
 Not sure if this is expected behavior, but maybe it would be best to use placeholder information instead of not creating the module altogether?

I'm just thinking that the user might want to generate the code while not having their sendgrid information at hand.

```
module.js:457
    throw err;
    ^

Error: Cannot find module './api/password-reset'
    at Function.Module._resolveFilename (module.js:455:15)
```

**Comment by diegohaz** [comment]
You are right. A workaround for now would be just putting anything as the answer and edit it later. It's located in only one place, the `.env` file, which isn't sent to git.

**Comment by jay-at-avido** [comment]
Thanks.
For cases where this functionality doesn't get generated when the project is first created (because the user skipped or anything else)  it would be super useful to have  the authentication endpoints or at least the reset password functionality as it's own separated sub-generator, so that you can have it generated or re-generated at any given point in time.

Maybe I'll add an issue about it in the future

**Comment by jessewriter** [comment]
I would recommend adding this to the directions:  when you set the environmental variables you will also have to set the sendGrid variable (if you choose to use it in the setup) or the app will fail to load in Heroku.  If you did not do so in the terminal it is easy enough to add in the heroku app settings page.

**Comment by diegohaz** [comment]
@jessewriter Do you mean adding it to README? I agree with that and would accept a PR.
