### ISSUE TITLE
returned data should not be at the top-level or the json response

### ISSUE THREAD

**Issue by jay-at-avido** [diegohaz/generator-rest#26]
I know this could be easily dismissed as "a matter of taste", but I just wanted to mention that returning the model data at the top level of the json document hierarchy is considered a bit of an antipattern and something that I see other open source codebases moving away from.

I don't remember where I last saw this matter discussed but a quick 1 minute google search I was able to find a couple of guidelines around which corroborate this approach:

https://google.github.io/styleguide/jsoncstyleguide.xml?showone=data#data

and also:

http://jsonapi.org/format/#document-top-level

**Comment by diegohaz** [comment]
I'm really appreciating your participation. Thank you very much. 😊 

Just to justify my decision to send the actual data on the top level, I became to ponder on this in the past, but I came to the conclusion that the vast majority of the metadata which I would send along the response I should do via HTTP headers (if there's not a native header for that, I should send some `X-Custom-Header` instead). So it became pointless to envelop the response.

Another reason is to make things simpler and let the user (the developer who uses the generator) decides the better approach. As this project greatly implements separation of concerns, it should be easy to implement by just changing the `services/response` module. :)

**Comment by diegohaz** [comment]
This project is heavily influenced by this post: http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

It talks about enveloping responses [here](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#envelope)
