### ISSUE TITLE
TypeError: request.body.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by tguelcan** [diegohaz/generator-rest#29]
Post a new Article

`curl -X POST http://0.0.0.0:9000/articles -i -d "title=Awesome Article&content=YeahBaby access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"`

`TypeError: request.body.hasOwnProperty is not a function at JwtStrategy.<anonymous> (.../node_modules/passport-jwt/lib/extract_jwt.js:30:42)`

Only on local version. It works on heroku. Any Idea?

Versions

IOS: 10.12
npm: 3.10.9
nodejs: 6.3.1
MongoDB: 3.2.8
passport-jwt "^2.1.0"

**Comment by diegohaz** [comment]
It might be related to #5

**Comment by diegohaz** [comment]
Try to do this https://github.com/diegohaz/generator-rest/issues/5#issuecomment-252920648

**Comment by tguelcan** [comment]
it works over querystring.. strange :) any updates about "passport-jwt" ? Thx a lot!!!

**Comment by diegohaz** [comment]
Not yet. There's an [open PR](https://github.com/themikenicholson/passport-jwt/pull/77) there that solves it. Leave your 👍 there so the maintainers can see it is needed. :)
