### ISSUE TITLE
Remove passport-jwt dependency

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/generator-rest#30]
Look for an alternative to that. The project is awesome, but seems unmaintained. There're old PRs unmerged (even people asking for that), like [one we need](https://github.com/themikenicholson/passport-jwt/pull/77), and the owner doesn't answer.

**Comment by QzSG** [comment]
@diegohaz You seemed to have started the ball rolling on the pr fixes in passport-jwt haha , this issue can still be left open as it might be good to start looking for an alternative while passport-jwt isn't totally dead yet

**Comment by diegohaz** [comment]
Yeah 😄 

Can someone confirm if it's working now? @PHILLIPS71 @aluengo @tguelcan

**Comment by diegohaz** [comment]
It seems to be working now. :)
