### ISSUE TITLE
Inconsistent Naming Convention Of Generated API

### ISSUE THREAD

**Issue by oelumeze** [diegohaz/generator-rest#35]
I Generated a sample API on an existing project with "yo rest:api" which resulted to the files named as indicated:
<img width="1219" alt="screen shot 2016-11-04 at 6 59 58 pm" src="https://cloud.githubusercontent.com/assets/11803701/20025304/7773931a-a2c3-11e6-8f30-a3f51d4f067e.png">

Wondering if this is an upgrade, or something i'm yet to do as compared to this:
<img width="1138" alt="screen shot 2016-11-04 at 6 52 28 pm" src="https://cloud.githubusercontent.com/assets/11803701/20025369/1c2302f6-a2c4-11e6-830c-630253648880.png">

Thanks.

**Comment by diegohaz** [comment]
Yes, this is an upgrade. See the [releases page](https://github.com/diegohaz/generator-rest/releases).

I suggest you to use the `v0.8.1` on existing projects.
```sh
npm install -g generator-rest@0.8.1
```

**Comment by oelumeze** [comment]
@diegohaz Thanks. It works now.
