### ISSUE TITLE
implementing logout?

### ISSUE THREAD

**Issue by aaronksaunders** [diegohaz/generator-rest#36]
The generator generates code for creating users, logging in, but nothing for logging out/ destroying the session.

Is there a recommended approach?

**Comment by diegohaz** [comment]
It uses JWT so the most simplest way to logout (which is the way I do on my apps) is just removing the token reference from the client (e.g. if you store it in cookies, just remove it from there).

There're other approaches. You can refer to this answer on SO: http://stackoverflow.com/a/23089839/5513909
