### ISSUE TITLE
Multiple exports

### ISSUE THREAD

**Issue by kdschaffe** [diegohaz/generator-rest#37]
Why do you have the models exporting in es2015 and commonjs formats?

See: https://github.com/diegohaz/generator-rest/blob/master/generators/api/templates/model.js#L48

**Comment by diegohaz** [comment]
Hi, @kdschaffe.

It was introduced in f6628c52df4fa4f99ae0567e2fd276789504ba7e

I wanted to remove the `babel-plugin-add-module-exports` dependency as the only file that leverages it is the `model.js`. The `module.exports` is needed there because in `index.js` we need to `exports Model, { schema } from 'model.js'`.

**Comment by kdschaffe** [comment]
Thanks for the quick response. I just wanted to clarify a little further in case anyone else is confused with how mixed modules systems work. 

One thing I noticed is that removing ```javascript export default mongoose.model('Model', schema)``` (es2015) from the model, didn't break anything. What actually gives support for ```javascript export Model, { schema } from './model'``` is babel and [statge-1](https://github.com/leebyron/ecmascript-more-export-from#compound-export-from-statements) preset. 

On the other hand, removing ```javascript module.exports ``` (commonjs) does cause something to break in ```javascript index.js``` but it's the named import ```javascript import { schema } from './model'  ```, not the export.

So what I still want to know for sure is how does ```javascript module.exports``` provide a named import.
And, is ```javascript export default ``` there for any reason other than consistency (using es2015 modules everywhere else)?

**Comment by kdschaffe** [comment]
I guess a better way to phrase this, would the export in the model be better with something like this:

```
const model = mongoose.model('Model', schema)
export const schema = model.schema
export default model
```

**Comment by diegohaz** [comment]
I like your last snippet. You are right, It looks better. Would you mind to send a PR with this change?

The files are:
- https://github.com/diegohaz/generator-rest/blob/master/generators/api/templates/model.js
- https://github.com/diegohaz/generator-rest/blob/master/generators/app/templates/api/user/model.js
- https://github.com/diegohaz/generator-rest/blob/master/generators/app/templates/api/password-reset/model.js

**Comment by kdschaffe** [comment]
Sure, no problem. Thanks
