### ISSUE TITLE
Angular 2 Basic Auth

### ISSUE THREAD

**Issue by divanvb** [diegohaz/generator-rest#48]
Hi, how would you send the request from the client side using angular 2 to authenticate the user and then send back the token with all the relevant details of the user? 

I've tried searching and it looks like you'll need to add headers to the post from the client side but not sure how to do that. Can you maybe give me an example?

**Comment by diegohaz** [comment]
You need to make a request equivalent to:

```
curl -X POST http://0.0.0.0:9000/auth -i -u test@example.com:123456 -d "access_token=MASTER_KEY_HERE"
```

How to do that on Angular 2 is out of the scope of this repo. It would be better for you to ask on StackOverflow or something related to Angular 2. I honestly never used Angular 2, so I'm not able to help you.
