### ISSUE TITLE
Appropriate usage of master key

### ISSUE THREAD

**Issue by Unilat** [diegohaz/generator-rest#49]
I'm fairly new to the concept of a master key. To me it makes sense as a "the dev who has this can get anything done", but by default it's middleware on the /auth endpoint and user creation. If I were to have a site that allows users to register themselves and to log themselves in... wouldn't that mean that they would need to have the master key stored locally? Am I misinterpreting how the master key is used? My understanding would be that both of these endpoints should have no authorization middleware.

Should I remove these from these two endpoints if that is the case?

**Comment by diegohaz** [comment]
`POST` requests should always be protected by some kind of `accesst_token`. Most of them will require user to be authenticated, so no problem.

But, obviously, when `POST /auth` and `POST /users` the user isn't authenticated yet, thus having no `access_token`. 

If those endpoints aren't protected, everyone can get an `access_token`, which means everyone can make `POST` requests on our servers.

The master key here is a solution to protect those `POST` requests that don't require user to be authenticated. This should not be exposed to the client. The `sign in` and `sign up` pages on your application should be rendered by a server and handled by a server (like we did in the old days for the entire website) and then it will store the `access_token` locally so the rest of the webapp (which can be a single page application) can use it.

If you want to make the `sign in` and `sign up` pages part of your SPA, running only on client. You must replace the master key for some referrer identification (e.g. verify on the API if the request comes from my website).

Tell me if it helps you.

**Comment by Unilat** [comment]
How would /auth be negative to expose without a master key? It requires an email and password in order to retrieve a JWT.

Putting user registration behind a non-SPA page makes sense. But if behind the scenes it's just a /login page followed by a form submission to /register and register is just calling the API, what's the point of the API to register users? Solely for admins having quick access? There's also nothing to stop people from just using the front-end UX to create random users. Is that he deterrent here? Allow people with a master key an endpoint to register users that only works with that key, and for everyone else there's the front end UI which means they can't spam (as easily) user creation?

Thanks for the help

**Comment by diegohaz** [comment]
> How would /auth be negative to expose without a master key? It requires an email and password in order to retrieve a JWT.

It just ensures that the auth has been made within your app. If this isn't a requirement for your use case, you can remove the master key protection as well (just remove the `master()` middleware).

You can put more and more security levels if you have those requirements (IP protection, referrer, client key, hash signatures, delay between requests etc.). If you do that, please share your thoughts. I want to improve the user/auth API for the v1.0.0 (see https://github.com/diegohaz/generator-rest/issues/32#issuecomment-263044351),
