### ISSUE TITLE
Payload to large

### ISSUE THREAD

**Issue by divanvb** [diegohaz/generator-rest#50]
Hi, when adding an object to the server, I get an error stating the payload is to large to add. I know what it is and I know how to fix it with these 2 lines.

app.use(bodyParser.json({ limit: '50mb', type: 'application/json' }))
app.use(bodyParser.urlencoded({ limit: '50mb', extended: true, parameterLimit: 50000 }))

I have overcome this problem on a previous server but I am struggling to get it to work with your sever which I am loving at the moment. Where I previously added these lines is in the index.js file where you export the "app" but It's not working.

Any advice?

**Comment by diegohaz** [comment]
It should be added to `src/services/express`

Tell me if it works. 👍
