### ISSUE TITLE
Query the database

### ISSUE THREAD

**Issue by divanvb** [diegohaz/generator-rest#51]
Hey man.

I see that when generating a new api, the get request that one can make with the master key etc it will return all the indexes/values. My question is I see with the get a query function is passed through

router.get('/', master(), query(),  index)

Now my question that I have is can I make a custom query sent from the client side with a get request to return only the desired values from the query?

**Comment by divanvb** [comment]
Haha no worries man, seems that you can. After a bit off googling I found the correct way to get the items 👍

**Comment by divanvb** [comment]
Havent gotten this to work.

**Comment by diegohaz** [comment]
Hi, @divanvb 

Did you see this? https://github.com/diegohaz/querymen

**Comment by divanvb** [comment]
Yes I di but Im struggling to a query from angular to the server

**Comment by divanvb** [comment]
this.http.get('http://10.0.0.6:9000/venues?access_token=5eAwHjqUhehOA2sOQDVDdmyk4zK35WNt&owner=' + ownerID)

How im trying to get a venue from only a specific user

**Comment by diegohaz** [comment]
Many people have asked me about Angular, but unfortunately I don't have much experience with the lib to help them. Worked with Angular 1.5 for just few months almost a year ago.

What I usually suggest is trying to make requests with [`curl`](https://curl.haxx.se/) first. Then count on Angular community to help to translate it to the *Angular way of life*.

About your specific case, you can define a querystring schema on `query()`

```js
query({ owner: mongoose.Schema.ObjectId })

// or just use the same schema field from your model
const { owner } = schema.tree
...
query({ owner })
```

**Comment by divanvb** [comment]
Where would I declare the querystring?

**Comment by diegohaz** [comment]
Do you mean here?
```js
router.get('/', master(), query(), index)
```

**Comment by divanvb** [comment]
Yeah

**Comment by divanvb** [comment]
As I understand your code:

`router.get('/', access_code='asdasd', owner='asdasd', index)`

**Comment by diegohaz** [comment]
You just need to define the querystring schema:
```js
router.get('/', master(), query({ owner: String }), index)
```

So it will parse requests like this: `http://0.0.0.0:9000/venues?owner=ownerId`

**Comment by divanvb** [comment]
You man are a champion. It's working 100% now by the looks of it.

My changes:

`return this.http.get('http://10.0.0.6:9000/venues?access_token=5eAwHjqUhehOA2sOQDVDdmyk4zK35WNt&owner=' + ownerID)
      .map(res => res.json())
      .catch((error:any) => Observable.throw(error.json().error || 'Server error'));`

router.get('/',
  master(),
  query({ owner: String }),
  index)

**Comment by diegohaz** [comment]
Yay! 🎉

Refer to the [`querymen`'s documentation](https://github.com/diegohaz/querymen). There're other things you can do like pagination (`/venues?page=2&limit=20`).
