### ISSUE TITLE
Can't retrieve data from db. 

### ISSUE THREAD

**Issue by etionsun** [diegohaz/generator-rest#52]
1.Create project and install npm.
2.Start mongo db.
3.Use postman to retrieve "users"  "GET" http://0.0.0.0:9000/users
3.1 try to add access_token behind URL (default MASTER_KEY)
3.2 try to add access_token in headers (default MASTER_KEY)

Result: 401 unauthorized
Expect: empty array.

**Comment by diegohaz** [comment]
Hi, @etionsun 

By default, `GET /users` needs an admin user's access token, as you can see on docs (`npm run docs`) and on the file (`src/api/user/index.js`):

```js
/**
 * @api {get} /users Retrieve users
 * @apiName RetrieveUsers
 * @apiGroup User
 * @apiPermission admin
 * @apiParam {String} access_token User access_token.
 * @apiUse listParams
 * @apiSuccess {Object[]} users List of users.
 * @apiError {Object} 400 Some parameters may contain invalid values.
 * @apiError 401 Admin access only.
 */
router.get('/',
  token({ required: true, roles: ['admin'] }), <------- here
  query(),
  index)
```

Of course, you can replace that `token(...)` by `master()` if you want, but take a look at https://github.com/diegohaz/generator-rest/issues/49#issuecomment-268416309 to understand what the master key is intended for.

Tell me if this helps you.

**Comment by etionsun** [comment]
Hi @diegohaz 

Yeah, it does make since and works now, thanks very much for your reply.

Bwt, I'd like to know if it is possible to regenerate docs after modified models? or any plan to integrate swagger?

**Comment by diegohaz** [comment]
You can always regenerate docs, just update the `/* @api */` comment blocks and run `npm run docs`
