### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by iovaandreia** [diegohaz/generator-rest#54]
I created a client app in Angular js, in this app you can log in as an user and add articles.  I merge my client with this server. I tried to log in with the user created in the terminal and everything i used (add Authorization: Bearer Access-Token in header request) i got this:
Request URL:http://0.0.0.0:9000/auth
Request Method:POST
Status Code:401 Unauthorized
Remote Address:0.0.0.0:9000

I used $http service.

Can you give me some advices?﻿

**Comment by diegohaz** [comment]
Hi, @iovaandreia. I can't really help you with Angular stuff, so I suggest you to try to do everything on terminal first (just follow [this section](https://github.com/diegohaz/generator-rest#playing-locally)) and, after that, count on Angular's community to help you to translate the relevant `curl` requests to `$http`.

Also, remember that `POST /auth` needs a Basic Auth header with email and password:
```
curl -X POST http://0.0.0.0:9000/auth -i -u test@example.com:123456 -d "access_token=MASTER_KEY_HERE"
```

**Comment by iovaandreia** [comment]
Hi,
  Thank you for the response, i think is nothing about the Angular,
anything else is working : create user, create article, delete article etc
, but when i try to login i got : 401 Unauthorized.

I don't understand very clearly what you mean in Doc:
I send an email to Angular Community and they said that is correct how i do.
I do not understand what server expect from me in the request.



Headers
NameTypeDescription
Authorization String

Basic authorization with email and password.
<https://github.com/diegohaz/generator-rest-example/blob/master/DOCS.md#parameters-4>
Parameters
NameTypeDescription
access_token String

Master access_token.

**Comment by diegohaz** [comment]
@iovaandreia Are you able to do this on terminal?
```
curl -X POST http://0.0.0.0:9000/auth -i -u test@example.com:123456 -d "access_token=MASTER_KEY_HERE"
```

If yes, just translate this to Angular. Make sure you are sending the right username and password.
