### ISSUE TITLE
Support Google login

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/generator-rest#7]
The same way Facebook and GitHub login was implemented, we need to:

 - create a `google` service with a `getMe` method in [generators/app/templates/services](https://github.com/diegohaz/generator-rest/tree/master/generators/app/templates/services)
 - enable the option on [generators/app/index.js#L51](https://github.com/diegohaz/generator-rest/blob/master/generators/app/index.js#L51)
 - add the option on [test/index.js#L8](https://github.com/diegohaz/generator-rest/blob/master/test/index.js#L8)

It's important to note that the API will only handle the token provided by Google and not the entire OAuth process (it must be done on the client).

This issue is participating on the [Digital Ocean's Hacktoberfest](https://hacktoberfest.digitalocean.com/).

**Comment by QzSG** [comment]
@diegohaz Hi again I couldn't resist contributing 😄. Tell me if there are any parts I forgot to edit
